server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: hotel-route
          uri: lb://hotel-service
          predicates:
            - Path=/api/hotels/**,/api/rooms/**
        - id: booking-route
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**,/api/booking/**,/api/user/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
